
### GET all candidates
GET http://localhost:7070/api/candidates
Accept: application/json

### GET candidates by category
GET http://localhost:7070/api/candidates/category/FRONTEND
Accept: application/json

### GET one candidate by ID
GET http://localhost:7070/api/candidates/5
Accept: application/json


### CREATE a new candidate
POST http://localhost:7070/api/candidates
Content-Type: application/json
Accept: application/json

{
  "name": "Emma Nielsen",
  "education": "Computer Science",
  "phone": "+4521123344"
}


### UPDATE a candidate
PUT http://localhost:7070/api/candidates/1
Content-Type: application/json
Accept: application/json

{
  "name": "Emma M. Nielsen",
  "education": "Data Science",
  "phone": "+4521987654"
}


###DELETE a candidate
DELETE http://localhost:7070/api/candidates/1
Accept: application/json

### CREATE NEW SKILL
POST http://localhost:7070/api/skills
Content-Type: application/json

{
  "name": "SQL",
  "description": "Containerization technology",
  "category": "DEVOPS"
}
### READ ALL SKILLS
GET http://localhost:7070/api/skills

### READ BY ID
GET http://localhost:7070/api/skills/1

### UPDATE SKILL
PUT http://localhost:7070/api/skills/1
Content-Type: application/json

{
  "name": "Kubernetes",
  "description": "Container orchestration",
  "category": "DEVOPS"
}

### DELETE SKILL
DELETE http://localhost:7070/api/skills/1

### ADD SKILL TO CANDIDATE
PUT http://localhost:7070/api/candidates/5/skills/9

